<?php

use Illuminate\Database\Seeder;

class CidadesSantaCatarinaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Abdon Batista', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Abelardo Luz', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Agrolândia', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Agronômica', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Água Doce', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Águas de Chapecó', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Águas Frias', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Águas Mornas', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Alfredo Wagner', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Alto Bela Vista', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Anchieta', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Angelina', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Anita Garibaldi', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Anitápolis', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Antônio Carlos', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Apiúna', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Arabutã', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Araquari', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Araranguá', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Armazém', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Arroio Trinta', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Arvoredo', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Ascurra', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Atalanta', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Aurora', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Balneário Arroio do Silva', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Balneário Barra do Sul', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Balneário Camboriú', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Balneário Gaivota', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Bandeirante', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Barra Bonita', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Barra Velha', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Bela Vista do Toldo', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Belmonte', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Benedito Novo', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Biguaçu', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Blumenau', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Bocaina do Sul', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Bom Jardim da Serra', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Bom Jesus', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Bom Jesus do Oeste', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Bom Retiro', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Bombinhas', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Botuverá', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Braço do Norte', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Braço do Trombudo', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Brunópolis', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Brusque', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Caçador', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Caibi', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Calmon', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Camboriú', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Campo Alegre', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Campo Belo do Sul', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Campo Erê', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Campos Novos', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Canelinha', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Canoinhas', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Capão Alto', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Capinzal', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Capivari de Baixo', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Catanduvas', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Caxambu do Sul', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Celso Ramos', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Cerro Negro', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Chapadão do Lageado', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Chapecó', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Cocal do Sul', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Concórdia', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Cordilheira Alta', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Coronel Freitas', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Coronel Martins', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Correia Pinto', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Corupá', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Criciúma', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Cunha Porã', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Cunhataí', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Curitibanos', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Descanso', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Dionísio Cerqueira', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Dona Emma', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Doutor Pedrinho', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Entre Rios', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Ermo', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Erval Velho', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Faxinal dos Guedes', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Flor do Sertão', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Florianópolis', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Formosa do Sul', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Forquilhinha', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Fraiburgo', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Frei Rogério', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Galvão', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Garopaba', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Garuva', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Gaspar', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Governador Celso Ramos', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Grão Pará', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Gravatal', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Guabiruba', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Guaraciaba', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Guaramirim', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Guarujá do Sul', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Guatambú', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Herval d`Oeste', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Ibiam', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Ibicaré', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Ibirama', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Içara', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Ilhota', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Imaruí', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Imbituba', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Imbuia', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Indaial', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Iomerê', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Ipira', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Iporã do Oeste', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Ipuaçu', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Ipumirim', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Iraceminha', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Irani', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Irati', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Irineópolis', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Itá', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Itaiópolis', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Itajaí', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Itapema', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Itapiranga', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Itapoá', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Ituporanga', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Jaborá', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Jacinto Machado', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Jaguaruna', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Jaraguá do Sul', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Jardinópolis', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Joaçaba', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Joinville', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'José Boiteux', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Jupiá', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Lacerdópolis', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Lages', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Laguna', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Lajeado Grande', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Laurentino', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Lauro Muller', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Lebon Régis', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Leoberto Leal', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Lindóia do Sul', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Lontras', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Luiz Alves', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Luzerna', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Macieira', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Mafra', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Major Gercino', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Major Vieira', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Maracajá', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Maravilha', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Marema', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Massaranduba', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Matos Costa', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Meleiro', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Mirim Doce', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Modelo', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Mondaí', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Monte Carlo', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Monte Castelo', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Morro da Fumaça', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Morro Grande', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Navegantes', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Nova Erechim', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Nova Itaberaba', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Nova Trento', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Nova Veneza', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Novo Horizonte', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Orleans', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Otacílio Costa', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Ouro', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Ouro Verde', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Paial', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Painel', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Palhoça', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Palma Sola', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Palmeira', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Palmitos', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Papanduva', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Paraíso', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Passo de Torres', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Passos Maia', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Paulo Lopes', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Pedras Grandes', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Penha', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Peritiba', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Petrolândia', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Piçarras', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Pinhalzinho', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Pinheiro Preto', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Piratuba', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Planalto Alegre', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Pomerode', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Ponte Alta', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Ponte Alta do Norte', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Ponte Serrada', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Porto Belo', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Porto União', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Pouso Redondo', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Praia Grande', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Presidente Castelo Branco', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Presidente Getúlio', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Presidente Nereu', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Princesa', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Quilombo', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Rancho Queimado', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Rio das Antas', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Rio do Campo', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Rio do Oeste', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Rio do Sul', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Rio dos Cedros', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Rio Fortuna', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Rio Negrinho', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Rio Rufino', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Riqueza', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Rodeio', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Romelândia', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Salete', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Saltinho', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Salto Veloso', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Sangão', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Santa Cecília', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Santa Helena', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Santa Rosa de Lima', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Santa Rosa do Sul', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Santa Terezinha', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Santa Terezinha do Progresso', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Santiago do Sul', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Santo Amaro da Imperatriz', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'São Bento do Sul', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'São Bernardino', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'São Bonifácio', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'São Carlos', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'São Cristovão do Sul', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'São Domingos', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'São Francisco do Sul', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'São João Batista', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'São João do Itaperiú', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'São João do Oeste', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'São João do Sul', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'São Joaquim', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'São José', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'São José do Cedro', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'São José do Cerrito', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'São Lourenço do Oeste', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'São Ludgero', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'São Martinho', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'São Miguel da Boa Vista', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'São Miguel do Oeste', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'São Pedro de Alcântara', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Saudades', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Schroeder', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Seara', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Serra Alta', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Siderópolis', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Sombrio', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Sul Brasil', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Taió', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Tangará', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Tigrinhos', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Tijucas', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Timbé do Sul', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Timbó', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Timbó Grande', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Três Barras', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Treviso', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Treze de Maio', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Treze Tílias', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Trombudo Central', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Tubarão', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Tunápolis', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Turvo', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'União do Oeste', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Urubici', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Urupema', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Urussanga', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Vargeão', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Vargem', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Vargem Bonita', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Vidal Ramos', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Videira', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Vitor Meireles', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Witmarsum', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Xanxerê', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Xavantina', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Xaxim', 'estado_id' => 24]);
        \App\Models\Localizacao\Cidade::create(['descricao' => 'Zortéa', 'estado_id' => 24]);

        $this->command->info('Cidades de Santa Catarina importadas com sucesso!');
    }
}
